// // const carsData = [
// //     {
// //         id: 1,
// //         make: "Toyota",
// //         model: "Innova Crysta",
// //         year: 2023,
// //         pricePerDay: 4500,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Diesel",
// //         seats: 7,
// //         rating: 4.6,
// //         image:
// //             "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?ixlib=rb-4.1.0&auto=format&fit=crop&q=60&w=600",
// //     },
// //     {
// //         id: 2,
// //         make: "Honda",
// //         model: "City",
// //         year: 2022,
// //         pricePerDay: 3800,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Petrol",
// //         seats: 5,
// //         rating: 4.5,
// //         image:
// //             "https://images.unsplash.com/photo-1594070319944-7c0cbebb6f58?ixlib=rb-4.1.0&auto=format&fit=crop&q=60&w=600",
// //     },
// //     {
// //         id: 3,
// //         make: "Hyundai",
// //         model: "Creta",
// //         year: 2023,
// //         pricePerDay: 4200,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Diesel",
// //         seats: 5,
// //         rating: 4.6,
// //         image:
// //             "https://images.unsplash.com/photo-1649921777129-a28a26031a03?ixlib=rb-4.1.0&auto=format&fit=crop&q=60&w=600",
// //     },
// //     {
// //         id: 4,
// //         make: "Maruti Suzuki",
// //         model: "Ertiga",
// //         year: 2024,
// //         pricePerDay: 4000,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Petrol",
// //         seats: 7,
// //         rating: 4.4,
// //         image:
// //             "https://images.pexels.com/photos/8766145/pexels-photo-8766145.jpeg",
// //     },
// //     {
// //         id: 5,
// //         make: "Tata",
// //         model: "Nexon",
// //         year: 2023,
// //         pricePerDay: 3900,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Petrol",
// //         seats: 5,
// //         rating: 4.5,
// //         image:
// //             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN3NbS2P5tBna3EQtSeyphRyxMZLJsruQveQ&s",
// //     },
// //     {
// //         id: 6,
// //         make: "Kia",
// //         model: "Carens",
// //         year: 2023,
// //         pricePerDay: 4300,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Diesel",
// //         seats: 7,
// //         rating: 4.7,
// //         image:
// //             "https://images.pexels.com/photos/7290405/pexels-photo-7290405.jpeg",
// //     },
// //     {
// //         id: 7,
// //         make: "Mahindra",
// //         model: "XUV300",
// //         year: 2022,
// //         pricePerDay: 3700,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Diesel",
// //         seats: 5,
// //         rating: 4.5,
// //         image:
// //             "https://images.pexels.com/photos/29057945/pexels-photo-29057945.jpeg",
// //     },
// //     {
// //         id: 8,
// //         make: "Renault",
// //         model: "Triber",
// //         year: 2023,
// //         pricePerDay: 3500,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Petrol",
// //         seats: 7,
// //         rating: 4.3,
// //         image:
// //             "https://images.pexels.com/photos/32462522/pexels-photo-32462522.jpeg",
// //     },
// //     {
// //         id: 9,
// //         make: "Nissan",
// //         model: "Magnite",
// //         year: 2023,
// //         pricePerDay: 3600,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Petrol",
// //         seats: 5,
// //         rating: 4.4,
// //         image:
// //             "https://images.news18.com/ibnlive/uploads/2021/10/nissan-magnite-long-term-review-feature-16349059464x3.jpg",
// //     },
// //     {
// //         id: 10,
// //         make: "Ford",
// //         model: "EcoSport",
// //         year: 2022,
// //         pricePerDay: 3800,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Diesel",
// //         seats: 5,
// //         rating: 4.5,
// //         image:
// //             "https://hips.hearstapps.com/hmg-prod/images/2018-ford-ecosport-mmp-1-1637615492.jpg?crop=1.00xw:0.957xh;0,0.0435xh&resize=2048:*",
// //     },
// //     {
// //         id: 11,
// //         make: "Maruti Suzuki",
// //         model: "Swift",
// //         year: 2023,
// //         pricePerDay: 3200,
// //         availability: true,
// //         transmission: "Manual",
// //         fuel: "Petrol",
// //         seats: 5,
// //         rating: 4.3,
// //         image:
// //             "https://images.pexels.com/photos/14238543/pexels-photo-14238543.jpeg",
// //     },
// //     {
// //         id: 12,
// //         make: "Hyundai",
// //         model: "Venue",
// //         year: 2024,
// //         pricePerDay: 4000,
// //         availability: true,
// //         transmission: "Automatic",
// //         fuel: "Diesel",
// //         seats: 5,
// //         rating: 4.6,
// //         image:
// //             "https://images.pexels.com/photos/11158776/pexels-photo-11158776.jpeg",
// //     },
// // ];

// // export default carsData;




// //  {
// "id": "6",
//     "make": "Kia",
//         "model": "Carens",
//             "year": 2023,
//                 "pricePerDay": 4300,
//                     "availability": true,
//                         "transmission": "Automatic",
//                             "fuel": "Diesel",
//                                 "seats": 7,
//                                     "rating": 4.7,
//                                         "image": "https://images.pexels.com/photos/7290405/pexels-photo-7290405.jpeg"
//     },
// {
//     "id": "7",
//         "make": "Mahindra",
//             "model": "XUV300",
//                 "year": 2022,
//                     "pricePerDay": 3700,
//                         "availability": true,
//                             "transmission": "Manual",
//                                 "fuel": "Diesel",
//                                     "seats": 5,
//                                         "rating": 4.5,
//                                             "image": "https://images.pexels.com/photos/29057945/pexels-photo-29057945.jpeg"
// },
// {
//     "id": "8",
//         "make": "Renault",
//             "model": "Triber",
//                 "year": 2023,
//                     "pricePerDay": 3500,
//                         "availability": true,
//                             "transmission": "Manual",
//                                 "fuel": "Petrol",
//                                     "seats": 7,
//                                         "rating": 4.3,
//                                             "image": "https://images.pexels.com/photos/32462522/pexels-photo-32462522.jpeg"
// },
// {
//     "id": "9",
//         "make": "Nissan",
//             "model": "Magnite",
//                 "year": 2023,
//                     "pricePerDay": 3600,
//                         "availability": true,
//                             "transmission": "Automatic",
//                                 "fuel": "Petrol",
//                                     "seats": 5,
//                                         "rating": 4.4,
//                                             "image": "https://images.news18.com/ibnlive/uploads/2021/10/nissan-magnite-long-term-review-feature-16349059464x3.jpg"
// },
// {
//     "id": "10",
//         "make": "Ford",
//             "model": "EcoSport",
//                 "year": 2022,
//                     "pricePerDay": 3800,
//                         "availability": true,
//                             "transmission": "Manual",
//                                 "fuel": "Diesel",
//                                     "seats": 5,
//                                         "rating": 4.5,
//                                             "image": "https://hips.hearstapps.com/hmg-prod/images/2018-ford-ecosport-mmp-1-1637615492.jpg?crop=1.00xw:0.957xh;0,0.0435xh&resize=2048:*"
// },
// {
//     "id": "11",
//         "make": "Maruti Suzuki",
//             "model": "Swift",
//                 "year": 2023,
//                     "pricePerDay": 3200,
//                         "availability": true,
//                             "transmission": "Manual",
//                                 "fuel": "Petrol",
//                                     "seats": 5,
//                                         "rating": 4.3,
//                                             "image": "https://images.pexels.com/photos/14238543/pexels-photo-14238543.jpeg"
// },
// {
//     "id": "12",
//         "make": "Hyundai",
//             "model": "Venue",
//                 "year": 2024,
//                     "pricePerDay": 4000,
//                         "availability": true,
//                             "transmission": "Automatic",
//                                 "fuel": "Diesel",
//                                     "seats": 5,
//                                         "rating": 4.6,
//                                             "image": "https://images.pexels.com/photos/11158776/pexels-photo-11158776.jpeg"
// }
